// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/backend/schema/structs/index.dart';
import '/actions/actions.dart' as action_blocks;
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'index.dart'; // Imports other custom widgets
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'dart:math' as math;

import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '/flutter_flow/custom_functions.dart';
import '/flutter_flow/lat_lng.dart';
import '/flutter_flow/place.dart';
import '/flutter_flow/uploaded_file.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '/auth/firebase_auth/auth_util.dart';

import 'package:fl_chart/fl_chart.dart';
import 'package:intl/intl.dart'; // for currency tooltip
import 'package:collection/collection.dart'; // for firstWhereOrNull

class PropertyProjectionChart2 extends StatefulWidget {
  const PropertyProjectionChart2({
    super.key,
    this.width,
    this.height,
    required this.projection, // Document: propertyProjections
    this.chartViewType = 'COMBINED', // 'CAPITAL' | 'RENTAL' | 'COMBINED'
    this.hasActiveTenancy = false, // handles no-tenancy case
  });

  final double? width;
  final double? height;

  // Generated by FF when you choose Document Type = propertyProjections
  final PropertyProjectionsRecord? projection;

  final String chartViewType;
  final bool hasActiveTenancy;

  @override
  State<PropertyProjectionChart2> createState() =>
      _PropertyProjectionChart2State();
}

class _PropertyProjectionChart2State extends State<PropertyProjectionChart2> {
  String _moneyShort(double v) {
    if (v.abs() >= 1000000) return '£${(v / 1000000).toStringAsFixed(1)}m';
    return '£${(v / 1000).round()}k';
  }

  double _toDouble(dynamic v, [double fallback = 0.0]) {
    if (v is num) return v.toDouble();
    if (v is String) {
      final parsed = double.tryParse(v);
      if (parsed != null) return parsed;
    }
    return fallback;
  }

  @override
  Widget build(BuildContext context) {
    final theme = FlutterFlowTheme.of(context);
    final proj = widget.projection;

    // Guard: no doc
    if (proj == null) {
      return SizedBox(
        width: widget.width ?? double.infinity,
        height: widget.height ?? 300,
        child:
            Center(child: Text('No projection data', style: theme.bodyMedium)),
      );
    }

    // --- Read arrays (null-safe + tolerant of null elements) ---
    final years = List<double>.from(
      (proj.years ?? const <dynamic>[]).map((e) => _toDouble(e)),
    );

    // Use the current field only; no legacy fallback
    final prices = List<double>.from(
      (proj.projectedHousePrice ?? const <dynamic>[]).map((e) => _toDouble(e)),
    );

    // Core length = min(years, prices)
    final coreLen = math.min(years.length, prices.length);
    if (coreLen < 2) {
      return SizedBox(
        width: widget.width ?? double.infinity,
        height: widget.height ?? 300,
        child: Center(
          child: Text('Not enough projection points', style: theme.bodyMedium),
        ),
      );
    }

    final y = years.take(coreLen).toList();
    final cap = prices.take(coreLen).toList();

    // Rental: if tenancy not active, treat as all zeros; also null-safe elements
    final rentalRaw = widget.hasActiveTenancy
        ? (proj.rental ?? const <dynamic>[])
        : const <dynamic>[];
    final ren = List<double>.generate(
      coreLen,
      (i) => i < rentalRaw.length ? _toDouble(rentalRaw[i]) : 0.0,
    );

    // Combined: if provided and long enough use it, else compute cap+ren
    List<double> comb;
    if (widget.hasActiveTenancy && (proj.combined?.length ?? 0) >= coreLen) {
      comb = List<double>.from(
        proj.combined!.take(coreLen).map((e) => _toDouble(e)),
      );
    } else {
      comb = List<double>.generate(coreLen, (i) => cap[i] + ren[i]);
    }

    // If tenancy is NOT active, force CAPITAL view (match old behavior)
    final effectiveViewType =
        (!widget.hasActiveTenancy && widget.chartViewType != 'CAPITAL')
            ? 'CAPITAL'
            : widget.chartViewType;

    // If user explicitly picked RENTAL but there’s no rent, show a friendly placeholder
    final rentalAllZero = ren.every((v) => v.abs() < 1e-9);
    if (effectiveViewType == 'RENTAL' && rentalAllZero) {
      return SizedBox(
        width: widget.width ?? double.infinity,
        height: widget.height ?? 300,
        child: Center(
          child:
              Text('No active tenancy — rental is £0', style: theme.bodyMedium),
        ),
      );
    }

    // Choose series
    late final List<FlSpot> dataToPlot;
    Color lineColor;
    Color gradientColor;

    switch (effectiveViewType) {
      case 'RENTAL':
        dataToPlot =
            List<FlSpot>.generate(coreLen, (i) => FlSpot(y[i], ren[i]));
        lineColor = const Color(0xFF33B56B);
        gradientColor = const Color(0xFF33B56B);
        break;
      case 'CAPITAL':
        dataToPlot =
            List<FlSpot>.generate(coreLen, (i) => FlSpot(y[i], cap[i]));
        lineColor = const Color(0xFFF2CB00); // Golden Yellow
        gradientColor = const Color(0xFFF2CB00);
        break;
      case 'COMBINED':
      default:
        dataToPlot =
            List<FlSpot>.generate(coreLen, (i) => FlSpot(y[i], comb[i]));
        lineColor = const Color(0xFF000080); // Navy
        gradientColor = const Color(0xFF000080);
        break;
    }

    // Bounds (handle flat/all-zero)
    final minX = y.first;
    final maxX = y.last;
    double minY = dataToPlot.map((s) => s.y).reduce(math.min);
    double maxY = dataToPlot.map((s) => s.y).reduce(math.max);
    if ((maxY - minY).abs() < 1e-9) {
      if (maxY == 0) {
        maxY = 1;
      } else {
        minY *= 0.95;
        maxY *= 1.05;
      }
    } else {
      if (minY > 0) minY *= 0.9;
      maxY *= 1.1;
    }

    final axisText = TextStyle(color: theme.secondaryText, fontSize: 11);
    final gridColor = theme.secondaryText.withOpacity(0.12);
    final axisLine = theme.secondaryText.withOpacity(0.35);

    final currencyFmt =
        NumberFormat.currency(locale: 'en_GB', symbol: '£', decimalDigits: 2);

    // Width depends on number of years
    const perYearPx = 60.0;
    final contentWidth =
        ((maxX - minX + 1) * perYearPx).clamp(perYearPx * 6, 30000.0);
    const rightPadding = 50.0;

    Widget bottomYear(double val, TitleMeta meta) {
      if ((val % 1).abs() > 0.0001) return const SizedBox.shrink();
      return Padding(
        padding: const EdgeInsets.only(top: 4),
        child: Text(val.toInt().toString(), style: axisText),
      );
    }

    final chart = LineChart(
      LineChartData(
        minX: minX,
        maxX: maxX,
        minY: minY,
        maxY: maxY,
        lineTouchData: LineTouchData(
          touchTooltipData: LineTouchTooltipData(
            getTooltipColor: (touchedSpot) => theme.secondary,
            tooltipPadding:
                const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
            getTooltipItems: (spots) => spots
                .map((s) => LineTooltipItem(
                      currencyFmt.format(s.y),
                      const TextStyle(color: Colors.white, fontSize: 12),
                    ))
                .toList(),
          ),
        ),
        gridData: FlGridData(
          show: true,
          drawVerticalLine: false,
          verticalInterval: 1.0,
          drawHorizontalLine: true,
          getDrawingHorizontalLine: (_) =>
              FlLine(color: gridColor.withOpacity(0.5), strokeWidth: 1),
        ),
        titlesData: FlTitlesData(
          bottomTitles: AxisTitles(
            sideTitles: SideTitles(
              showTitles: true,
              reservedSize: 24,
              getTitlesWidget: bottomYear,
            ),
          ),
          leftTitles: AxisTitles(
            sideTitles: SideTitles(
              showTitles: true,
              reservedSize: 60,
              getTitlesWidget: (val, meta) {
                if (val == minY || val == maxY) return const SizedBox.shrink();
                return Padding(
                  padding: const EdgeInsets.only(right: 0),
                  child: Text(_moneyShort(val), style: axisText),
                );
              },
            ),
          ),
          rightTitles:
              const AxisTitles(sideTitles: SideTitles(showTitles: false)),
          topTitles:
              const AxisTitles(sideTitles: SideTitles(showTitles: false)),
        ),
        borderData: FlBorderData(
          show: true,
          border: Border(
            left: BorderSide(color: axisLine, width: 1.5),
            bottom: BorderSide(color: axisLine, width: 1.5),
          ),
        ),
        lineBarsData: [
          LineChartBarData(
            spots: dataToPlot,
            isCurved: true,
            color: lineColor.withOpacity(0.9),
            barWidth: 3,
            belowBarData: BarAreaData(
              show: true,
              gradient: LinearGradient(
                colors: [
                  gradientColor.withOpacity(0.4),
                  gradientColor.withOpacity(0.0),
                ],
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
              ),
            ),
            dotData: const FlDotData(show: false),
          ),
        ],
      ),
    );

    return SizedBox(
      width: widget.width ?? double.infinity,
      height: widget.height ?? 300,
      child: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        physics: const BouncingScrollPhysics(),
        child: SizedBox(
          width: contentWidth + rightPadding,
          child: chart,
        ),
      ),
    );
  }
}
